project_name: node-dive
release:
  github:
    owner: caiobegotti
    name: node-dive
builds:
  - id: node-dive
    goos:
    - linux
    - windows
    - darwin
    goarch:
    - amd64
    - "386"
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: cmd/plugin/main.go
    ldflags: -s -w
      -X github.com/caiobegotti/node-dive/pkg/version.version=
archives:
  - id: node-dive
    builds:
    - node-dive
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
    - goos: windows
      format: zip
